M48
; DRILL file {KiCad 9.0.4} date 2025-09-17T13:52:34+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-17T13:52:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
%
G90
G05
T1
X105.249Y-79.799
X105.249Y-109.899
X185.249Y-79.799
X185.249Y-109.899
M30
